// Generated by CoffeeScript 1.6.3
(function() {
  var constructList, delay, isBusy, load, loadData, loadDataAfterOrBefore, months, processAll, processData, processDate, processTrending, selectedDate, setLoaderRotate, showAllData;

  selectedDate = null;

  isBusy = null;

  $(document).ready(function() {
    return load();
  });

  load = function() {
    setLoaderRotate(true);
    delay(1000, loadData);
    $('.leftArrow').click(function() {
      return loadDataAfterOrBefore(-1);
    });
    $('.rightArrow').click(function() {
      return loadDataAfterOrBefore(1);
    });
    return $('.find').click(function() {
      return showAllData();
    });
  };

  setLoaderRotate = function(status) {
    var clockClass, rotateClass;
    rotateClass = 'rotate';
    clockClass = '.clock';
    if (status) {
      return $(clockClass).addClass(rotateClass);
    } else {
      return $(clockClass).removeClass(rotateClass);
    }
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  loadData = function(date) {
    $('.all').fadeOut();
    isBusy = 1;
    return $.getJSON('/cgi-bin/nouveler-cgi.perl', {
      format: 'json',
      date: date
    }).done(function(data) {
      processData(JSON.parse(JSON.stringify(data)));
      isBusy = 0;
      return setLoaderRotate(false);
    });
  };

  loadDataAfterOrBefore = function(day) {
    var intDate;
    if (!isBusy) {
      intDate = selectedDate.getDate() + day;
      selectedDate.setDate(intDate);
      return loadData(selectedDate.getTime() / 1000);
    }
  };

  processData = function(data) {
    processDate(data.date);
    processTrending(data.hot);
    return processAll(data.data);
  };

  months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

  processDate = function(timestamp) {
    var date;
    date = new Date(timestamp * 1000);
    selectedDate = date;
    $('.day').html(date.getDate());
    $('.month').html(months[date.getMonth()]);
    return $('.year').html(date.getFullYear());
  };

  processTrending = function(trending) {
    var text;
    text = constructList(trending);
    return $('.trending').html(text);
  };

  processAll = function(all) {
    var text;
    text = constructList(all);
    return $('.all').html(text);
  };

  constructList = function(json) {
    var returnList, row, _i, _len;
    returnList = '<ul>';
    for (_i = 0, _len = json.length; _i < _len; _i++) {
      row = json[_i];
      returnList = returnList + '<li>' + row.title + '</li>';
    }
    return returnList + '</ul>';
  };

  showAllData = function() {
    if (!isBusy) {
      return $('.all').fadeIn();
    }
  };

}).call(this);
