// Generated by CoffeeScript 1.6.3
/*
Global Variable, i know it s bad
*/


(function() {
  var constructList, delay, isBusy, jQueryFadeSpeed, load, loadData, loadDataAfterOrBefore, months, processAll, processData, processDate, processTrending, selectedDate, setLoaderRotate;

  selectedDate = null;

  isBusy = null;

  jQueryFadeSpeed = 'slow';

  months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

  /*
  Bootstrap of App
  */


  $(document).ready(function() {
    return load();
  });

  /*
  Load data for today
  Activate animation
  */


  load = function() {
    delay(1000, loadData);
    $('.leftArrow').click(function() {
      return loadDataAfterOrBefore(-1);
    });
    $('.rightArrow').click(function() {
      return loadDataAfterOrBefore(1);
    });
    return $('.find').click(function() {
      if (!isBusy) {
        return $('.all').fadeToggle();
      }
    });
  };

  /*
  Activate or desactivate
  */


  setLoaderRotate = function(status) {
    var clockClass, rotateClass;
    rotateClass = 'rotate';
    clockClass = '.clock';
    if (status) {
      return $(clockClass).addClass(rotateClass);
    } else {
      return $(clockClass).removeClass(rotateClass);
    }
  };

  /*
  Delay Function
  */


  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  loadData = function(date) {
    setLoaderRotate(true);
    $('.all').fadeOut();
    isBusy = 1;
    return $.getJSON('/cgi-bin/nouveler-cgi.perl', {
      format: 'json',
      date: date
    }).done(function(data) {
      processData(JSON.parse(JSON.stringify(data)));
      isBusy = 0;
      return setLoaderRotate(false);
    });
  };

  /*
  Load data for the day (-/+) difference pass as argument
  */


  loadDataAfterOrBefore = function(day) {
    var intDate;
    if (!isBusy) {
      intDate = selectedDate.getDate() + day;
      selectedDate.setDate(intDate);
      return loadData(selectedDate.getTime() / 1000);
    }
  };

  /*
  Fade data + date, then inject new date / hot / data into the document
  */


  processData = function(data) {
    var fadeClass;
    fadeClass = '.fade';
    return $(fadeClass).fadeOut(jQueryFadeSpeed, function() {
      processDate(data.date);
      processTrending(data.hot);
      processAll(data.data);
      return $(fadeClass).fadeIn(jQueryFadeSpeed);
    });
  };

  /*
  Create a new date from a given timestamp, then inject date,month,year into the document
  */


  processDate = function(timestamp) {
    var date;
    date = new Date(timestamp * 1000);
    selectedDate = date;
    $('.day').html(date.getDate());
    $('.month').html(months[date.getMonth()]);
    return $('.year').html(date.getFullYear());
  };

  /*
  Build a ul/li list from json object then inject it into trending
  */


  processTrending = function(trending) {
    var text;
    text = constructList(trending);
    return $('.trending').html(text);
  };

  /*
  Get a ul/li list from json object then inject it into all
  */


  processAll = function(all) {
    var text;
    text = constructList(all);
    return $('.all').html(text);
  };

  /*
  Build a ul/li list from a json object
  */


  constructList = function(json) {
    var returnList, row, _i, _len;
    if (json[0]) {
      returnList = '<ul>';
      for (_i = 0, _len = json.length; _i < _len; _i++) {
        row = json[_i];
        returnList = returnList + '<li>' + row.title + '</li>';
      }
      return returnList + '</ul>';
    } else {
      return '<p>Their is no availaible data back at that time</p>';
    }
  };

}).call(this);
